/************************************* Final Version* Xiangbo Wang / xbwang@uchicago.edu* Problem2************************************///the cout maynot flush#include <iostream>#include <stdexcept>using namespace std;struct auto_flush {    auto_flush() {}    ~auto_flush() {         cout.flush();        cout << "--flush called--";    }};int g(){    throw runtime_error("g()'s dummy runtime error");    return -1;}int h(){    throw runtime_error("h()'s dummy runtime error");    return -1;}int f(){    try{        auto_flush af;        cout << "Some text";        g();        cout << h();        }catch(...) {            // destructor of auto_flush will be called            // nomatter an exception is catched or not        }    cout.flush();    return 0;}int main(){    f();    return 0;}